<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2bd7e7c4-62ca-4ada-85e3-da46b1264a22</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Apm.NetCoreAll" Version="1.34.5" />
    <PackageReference Include="Elastic.Apm.SerilogEnricher" Version="9.0.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.17.1" />
    <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.5.10" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.CorrelationId" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.Ong.Esperanca.Solidaria.Contracts\Fiap.Ong.Esperanca.Solidaria.Contracts.csproj" />
    <ProjectReference Include="..\Fiap.Ong.Esperanca.Solidaria.Worker.Application\Fiap.Ong.Esperanca.Solidaria.Worker.Application.csproj" />
    <ProjectReference Include="..\Fiap.Ong.Esperanca.Solidaria.Worker.Domain\Fiap.Ong.Esperanca.Solidaria.Worker.Domain.csproj" />
    <ProjectReference Include="..\Fiap.Ong.Esperanca.Solidaria.Worker.Infra.Data\Fiap.Ong.Esperanca.Solidaria.Worker.Infra.Data.csproj" />
  </ItemGroup>

</Project>
